theme: jekyll-theme-minimal
title: Yuxin Fan
#tagline:          A short tagline
#description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: https://yuxin-fan.github.io/
